# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('liked_num', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_ori', models.BooleanField(default=True)),
                ('is_gra', models.BooleanField(default=False)),
                ('is_bin', models.BooleanField(default=False)),
                ('is_gau', models.BooleanField(default=False)),
                ('is_sca', models.BooleanField(default=False)),
                ('is_rot', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
