# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0002_auto_20170702_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='origin',
            field=models.IntegerField(default=1),
        ),
    ]
