# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0004_img_saved_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(default=0)),
                ('to_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.IntegerField(default=0)),
                ('star_id', models.IntegerField(default=0)),
                ('pic_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.IntegerField(default=0)),
                ('star_id', models.IntegerField(default=0)),
                ('pic_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('liked_num', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('pic_num', models.IntegerField(default=0)),
                ('saved_num', models.IntegerField(default=0)),
                ('invite_num', models.IntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
