# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0005_invite_like_save_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='IMG_User',
        ),
    ]
