# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meitu', '0006_auto_20170704_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='fan_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='pic_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='star_id',
        ),
        migrations.RemoveField(
            model_name='save',
            name='fan_id',
        ),
        migrations.RemoveField(
            model_name='save',
            name='pic_id',
        ),
        migrations.RemoveField(
            model_name='save',
            name='star_id',
        ),
        migrations.AddField(
            model_name='like',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meitu.IMG'),
        ),
        migrations.AddField(
            model_name='save',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='save',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meitu.IMG'),
        ),
    ]
