# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0007_auto_20170704_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_user',
            name='save_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='img_user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='img_user',
            name='storage',
            field=models.IntegerField(default=60),
        ),
    ]
