# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0008_auto_20170704_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='is_con',
            field=models.BooleanField(default=False),
        ),
    ]
