# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meitu', '0010_auto_20170705_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='parent_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
